### ISSUE TITLE
Encounter Error when trying to load .so file

### ISSUE THREAD

**Issue by avonb** [nh2/call-haskell-from-anything#16]
Hey,

I created a simple Haskell file containing one function and the 

`foreign export ccall chooseMax_export :: CString -> IO CString`
`chooseMax_export = export chooseMax`

part from the readme. Then I compiled it to a .so with:

`sudo ghc --make -dynamic -shared -fPIC Java2Haskell.hs -o Java2Haskell.so`

when I try to load it in Python or Java I encounter this error:

`Traceback (most recent call last):`
`File "test.py", line 15, in <module>`
`lib = cdll.LoadLibrary(so_file_path)`
`File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary`
`return self._dlltype(name)`
`File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__`
`self._handle = _dlopen(self._name, mode)`
`OSError: /usr/lib/ghc/ghcpr_8TmvWUcS1U1IKHT0levwg3/libHSghc-prim-0.4.0.0-8TmvWUcS1U1IKHT0levwg3-ghc7.10.3.so: undefined symbol: stg_forkOnzh`

**Comment by nh2** [comment]
Please check if the same is happening when building with a .cabal file based on my example cabal file at https://github.com/nh2/call-haskell-from-anything/blob/master/call-haskell-from-anything.cabal

That may help us find out if your GHC invocation is sufficient.

For example, you did not specify `-no-hs-main` as I specify in https://github.com/nh2/call-haskell-from-anything/blob/master/call-haskell-from-anything.cabal#L64

**Comment by avonb** [comment]
Thanks, I didn't know, that I had to compile it with the cabal file.

**Comment by nh2** [comment]
You don't necessarily have to compile with the cabal file, but you'll have to supply the right options to ghc, and the cabal file can help with that. You can also use `cabal -v` (or even more verbose output, I don't remember if it's like `-vvv` or `-v3`) in order to see with what options cabal invokes ghc.
