### ISSUE TITLE
decoding problem with doubles

### ISSUE THREAD

**Issue by mwotton** [nh2/call-haskell-from-anything#20]
using this haskell:

```
foreign export ccall iddub_export :: CString -> IO CString
iddub_export = export iddub
iddub :: Double -> Double
iddub = id
```

and this python

```
# Some shortcuts
def make_msgpack_fun(fun):
    fun.restype = c_char_p

    def f(*args):
        return msgpack.unpackb(fun(msgpack.packb(args)))

    return f

iddub = make_msgpack_fun(lib.iddub_export)
for i in [1.01,1.001,1.0001]:
    print(i)
    print(iddub(i))
```

i get this rather weird message:

```
1.01
1.01
1.001
1.001
1.0001
<unknown>: Data.Binary.Get.runGet at position 1: Data.Binary.Get(Alternative).empty
CallStack (from HasCallStack):
  error, called at src/Data/Binary/Get.hs:321:5 in binary-0.7.6.1-A5o7SPwyA2mJ8cbNniVomK:Data.Binary.Get
```

could the parsing of floats be wrong somehow? it also happens with 1.0.

**Comment by nh2** [comment]
I'm very sorry, big mistake on my side. Can you tell me if [this branch](https://github.com/nh2/call-haskell-from-anything/tree/issue-20) fixes it?

**Comment by nh2** [comment]
I force pushed the branch to enforce the byte order to big-endian, like MessagePack does.

**Comment by mwotton** [comment]
/me reads issues

Good lord, what a weird stroke of luck that it worked on the examples :) i honestly thought i was going mad.

**Comment by nh2** [comment]
> Good lord

My words when I realised the issue. Pretty obvious in hindsight.

**Comment by mwotton** [comment]
```
➜  git:(master) ✗ python3 glue.py
<unknown>: user error (Data.ByteString.packCStringLen: negative length: -7869125547252892304)
```

what i'm getting with that branch.

**Comment by nh2** [comment]
@mwotton You have to update your python wrapper as I did [here](https://github.com/nh2/call-haskell-from-anything/commit/f5f1fbbfc72d6bbd11b564b467dad738d4f3e2e7#diff-b284a28710cce90d9d9be3a7f4cabc8eR37-R47) in case you haven't done that yet

**Comment by mwotton** [comment]
haha, oops :) yep, works great. Thanks!

**Comment by nh2** [comment]
OK, I've pushed it to master and published it as https://hackage.haskell.org/package/call-haskell-from-anything-1.1.0.0
