### ISSUE TITLE
Update to msgpack-1.0

### ISSUE THREAD

**Issue by nh2** [nh2/call-haskell-from-anything#5]
Development on the `mspack` has recently resumed with [`msgpack-1.0.0`](https://hackage.haskell.org/package/msgpack-1.0.0) being released.

`call-haskell-from-anything` should be updated to this, in particular because the new version is compatible with newer libraries without `--allow-newer` (I'm using it [here in Travis](https://travis-ci.org/nh2/call-haskell-from-anything/jobs/61278874#L184), and have asked for a point release to 0.7 [here](https://github.com/msgpack/msgpack-haskell/issues/57) to fix these problems).

This will need a bit of work though becasue the new version updated to [using `binary` for the Unpacker](https://github.com/msgpack/msgpack-haskell/commit/5943a99b2c80a0a6d367617f23043ac39c6860cd).

I'm not going to work on this very soon, unless somebody needs this urgently - in this case ping me here in this issue. PRs are also welcome.

**Comment by jhegedus42** [comment]
Hi

Indeed this would be useful. Since now, with latest GHC (7.10.2) I cannot compile/build this library.

It requires msgpack-1.0.0. It would be lovely to run this lib with latest GHC. Any idea how to fix that ?

**Comment by nh2** [comment]
Done with the now-released version `0.2.0.0`.

**Comment by jhegedus42** [comment]
Many thanks !
